version: "3.9"

services:
  backend:
    image: skyeye_backend
    restart: on-failure
    depends_on:
      - database
    volumes:
      - static:/app/static
    env_file:
      - .env
  frontend:
    image: skyeye_frontend
    volumes:
      - dist:/app/dist
      - ./prev_dist:/app/prev_dist
    env_file:
      - .env
  database:
    image: "postgres:12.11-alpine3.16" # use latest official postgres version
    restart: on-failure
    env_file: .env
  webserver:
    image: caddy:2.6.2-alpine
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - dist:/usr/share/caddy/frontend
      - static:/usr/share/caddy/django_static/static

    depends_on:
      - frontend
      - backend

volumes:
  static: {}
  dist: {}
  caddy_data: {}
  caddy_config: {}
